apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: enmasse-operators
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: enmasse
  displayName: "EnMasse Operators"
  publisher: "EnMasse"