apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: messaging-streams
  namespace: openshift-marketplace
spec:
  csDisplayName: Community Operators
  csPublisher: Community
  packages: strimzi-kafka-operator
  targetNamespace: messaging