apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace:  messaging
spec:
  channel: stable
  installPlanApproval: Automatic
  name: strimzi-kafka-operator
  source: messaging-streams
  sourceNamespace: messaging
  startingCSV: strimzi-cluster-operator.v0.11.1